---
title: 'QQ-plots: Example'
author: "Ralph Trane"
date: "2/11/2020"
output: html_document
---

Create ids

```{r}
is <- sample(1:12)
```

Simulate 11 data sets from normal with sample size 100

```{r}
X <- Normal()

many_small_normal <- data.frame(i = is[1:11]) %>% 
  mutate(distribution = "Normal",
         sample = map(i, random, d = X, n = 100)) %>% ## for each i, use random with d = Normal(), n = 10
  unnest_longer(col = sample)
```

Simulate 1 data set from the uniform distribution.

```{r}
U <- Uniform()
one_uniform_sample <- data.frame(i = is[12]) %>% 
  mutate(Distribution = "Uniform",
         sample = map(i, random, d = U, n = 100)) %>% 
  unnest_longer(col = sample)
```

Combine all samples into one big data set.

```{r}
all_12_samples <- bind_rows(
  many_small_normal,
  one_uniform_sample
) %>% 
  group_by(i) %>% 
  mutate(m = mean(sample),
         s = sd(sample))
```

Create QQ-plots.

```{r}
ggplot(data = all_12_samples,
       aes(sample = sample, group = i)) + 
  geom_qq() + 
  geom_abline(aes(intercept = m, slope = s)) + 
  facet_wrap(~i, ncol = 4, scales = "free") + 
  theme_bw() + 
  theme(axis.text = element_blank())
```


```{r}
all_12_samples %>% select(i, distribution) %>% unique()
```


The pmf for the binomial random variable with size n and probability of success $\pi$ is $P(X = k) = {n \choose k} \pi^k (1-\pi)^{n-k}$
