on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("pagedown", "rmarkdown", "stringr"))
        shell: Rscript {0}
      - name: Render index.Rmd
        run: rmarkdown::render("index.Rmd")
        shell: Rscript {0}
