on:
  push:
    paths:
      - docs/index.Rmd

name: Build

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "stringr", "pagedown"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd")'
      - name: Push new index.html
        run: |
          git commit docs/index.html -m 'Re-build index.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
          
